
use_default_settings: true

server:
  port: 8080
  bind_address: "0.0.0.0"
  secret_key: "searqon_secret_key_change_me"
  limiter: false

search:
  safe_search: 0
  autocomplete: ""
  formats:
    - html
    - json

outgoing:
  request_timeout: 8.0
  max_request_timeout: 15.0
